CREATE OR REPLACE TRIGGER TRG_AD_ZNTITEMCONF_SYNC
FOR INSERT OR UPDATE ON AD_FECCAR
COMPOUND TRIGGER

    TYPE t_nufechamento IS TABLE OF AD_FECCAR.NUFECHAMENTO%TYPE;
    v_lista_nufechAMENTO t_nufechamento := t_nufechamento();

    AFTER EACH ROW IS
    BEGIN
        IF NOT (v_lista_nufechAMENTO.EXISTS(:NEW.NUFECHAMENTO)) THEN
            v_lista_nufechAMENTO.EXTEND;
            v_lista_nufechAMENTO(v_lista_nufechAMENTO.LAST) := :NEW.NUFECHAMENTO;
        END IF;
    END AFTER EACH ROW;

    AFTER STATEMENT IS
        V_NUUNICO    NUMBER;
        V_ULTIMO_REG NUMBER;
    BEGIN
        FOR i IN 1..v_lista_nufechAMENTO.COUNT LOOP
            
            -- 1. VERIFICA OU CRIA O CABEÇALHO (AD_ZNTCONFCAB)
            BEGIN
                SELECT NUUNICO INTO V_NUUNICO 
                FROM AD_ZNTCONFCAB 
                WHERE NUFECHAMENTO = v_lista_nufechAMENTO(i);
            EXCEPTION WHEN NO_DATA_FOUND THEN
                -- Gera o próximo NUUNICO
                SELECT NVL(MAX(NUUNICO), 0) + 1 INTO V_NUUNICO FROM AD_ZNTCONFCAB;
                
                -- Insere apenas os campos permitidos
                INSERT INTO AD_ZNTCONFCAB (NUUNICO, NUFECHAMENTO, CONFERIDO)
                VALUES (V_NUUNICO, v_lista_nufechAMENTO(i), 'N');
            END;

            -- 2. BUSCA O ÚLTIMO NUMREG PARA OS ITENS DESTE NUUNICO
            SELECT NVL(MAX(NUMREG), 0) INTO V_ULTIMO_REG 
            FROM AD_ZNTITEMCONF 
            WHERE NUUNICO = V_NUUNICO;

            -- 3. REMOVE ITENS NÃO CONFERIDOS
            DELETE FROM AD_ZNTITEMCONF 
            WHERE NUUNICO = V_NUUNICO 
              AND NVL(CONFERIDO, 'N') <> 'S';

            -- 4. INSERE OS ITENS ATUALIZADOS
            INSERT INTO AD_ZNTITEMCONF (
                NUMREG, NUUNICO, NUFECHAMENTO, CODPROD, CODVOL, MARCA, DESCVOL, EAN, DUN, QUANT, CONFERIDO
            )
            SELECT 
                V_ULTIMO_REG + ROW_NUMBER() OVER (ORDER BY ORIGEM DESC, CODPROD),
                V_NUUNICO,
                v_lista_nufechAMENTO(i),
                CASE WHEN REGEXP_LIKE(D.CODPROD, '^[0-9]+$') THEN TO_NUMBER(D.CODPROD) ELSE NULL END,
                D.CODVOL,
                D.MARCA,
                D.DESCRDANFE,
                TO_NUMBER(SUBSTR(REGEXP_REPLACE(D.REFERENCIA, '[^0-9]', ''), 1, 15)),
                TO_NUMBER(SUBSTR(REGEXP_REPLACE(D.CODBARRA4DIG, '[^0-9]', ''), 1, 15)),
                ROUND(NVL(D.QTDNEG, 0), 0),
                'N'
            FROM (
                -- PARTE 1: TGF
                SELECT 'O' AS ORIGEM, TO_CHAR(ITE.CODPROD) AS CODPROD, ITE.CODVOL, NVL(PRO.MARCA, ' ') AS MARCA, 
                       NVL(VOA.DESCRDANFE, ' ') AS DESCRDANFE, PRO.REFERENCIA, SUBSTR(BAR.CODBARRA, -4) AS CODBARRA4DIG, 
                       SUM((CASE WHEN VOA.CODPROD IS NULL THEN ITE.QTDNEG WHEN VOA.DIVIDEMULTIPLICA = 'D' THEN ITE.QTDNEG * VOA.QUANTIDADE ELSE ITE.QTDNEG / VOA.QUANTIDADE END)) AS QTDNEG
                FROM AD_FECCAR FEC
                INNER JOIN AD_FECCOM COM ON FEC.NUFECHAMENTO = COM.NUFECHAMENTO
                INNER JOIN TGFCAB CAB ON CAB.ORDEMCARGA = COM.NUMDOCUMENTO
                INNER JOIN TGFITE ITE ON ITE.NUNOTA = CAB.NUNOTA
                INNER JOIN TGFPRO PRO ON ITE.CODPROD = PRO.CODPROD
                LEFT JOIN TGFVOA VOA ON (VOA.CODPROD = ITE.CODPROD AND VOA.CODVOL = ITE.CODVOL AND (ITE.CONTROLE IS NULL OR ITE.CONTROLE = VOA.CONTROLE))
                LEFT JOIN TGFVOA BAR ON (BAR.CODPROD = ITE.CODPROD AND BAR.UNIDTRIB = 'S' AND (ITE.CONTROLE IS NULL OR ITE.CONTROLE = BAR.CONTROLE))
                WHERE FEC.NUFECHAMENTO = v_lista_nufechAMENTO(i) AND CAB.TIPMOV = 'P' AND COM.TIPO = 'O'
                GROUP BY TO_CHAR(ITE.CODPROD), ITE.CODVOL, SUBSTR(BAR.CODBARRA, -4), PRO.MARCA, VOA.DESCRDANFE, PRO.REFERENCIA
                
                UNION ALL
                
                -- PARTE 2: TMS
                SELECT 'C', NVL(TO_CHAR(PRO.CODPROD),'0'), NVL(VOA.CODVOL,ITE.CODVOL), NVL(PRO.MARCA,' '), 
                       NVL(VOA.DESCRDANFE,' '), NVL(PRO.REFERENCIA,' '), ' ', SUM(ITE.QTDNEG)
                FROM TMSNOTAS NOTA 
                INNER JOIN TMSNOTASITE ITE ON NOTA.NROUNICO = ITE.NROUNICO
                INNER JOIN AD_FECCOM COM ON NOTA.NUNOTACTE = COM.NUMDOCUMENTO
                INNER JOIN AD_FECCAR FEC ON FEC.NUFECHAMENTO = COM.NUFECHAMENTO
                LEFT JOIN TGFPAP PAP ON PAP.CODPROPARC = ITE.CODPROPARC AND NOTA.CODPARCREM = PAP.CODPARC AND ITE.CODVOL = PAP.UNIDADE
                LEFT JOIN TGFPRO PRO ON PAP.CODPROD = PRO.CODPROD
                LEFT JOIN TGFVOA VOA ON PRO.CODPROD = VOA.CODPROD AND PAP.UNIDADEPARC = VOA.CODVOL
                WHERE FEC.NUFECHAMENTO = v_lista_nufechAMENTO(i) AND COM.TIPO = 'C'
                GROUP BY NVL(TO_CHAR(PRO.CODPROD),'0'), NVL(VOA.CODVOL,ITE.CODVOL), NVL(PRO.MARCA,' '), NVL(VOA.DESCRDANFE,' '), NVL(PRO.REFERENCIA,' ')
            ) D
            WHERE NOT EXISTS (
                SELECT 1 FROM AD_ZNTITEMCONF X 
                WHERE X.NUUNICO = V_NUUNICO 
                  AND X.CODPROD = CASE WHEN REGEXP_LIKE(D.CODPROD, '^[0-9]+$') THEN TO_NUMBER(D.CODPROD) ELSE NULL END 
                  AND X.CONFERIDO = 'S'
            );

        END LOOP;
    END AFTER STATEMENT;
END;